version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    ports:
      - "8000:9000"
    volumes:
      - .:/var/www/html
    networks:
      - laravel-network

networks:
  laravel-network:
